### PR TITLE
test: isolate the unit suite to stop cross-file mock pollution

### PR DESCRIPTION
**Pull request by duyet**
## Problem

Bun runs every test file in one process and `mock.module()` is a **global, persistent** override not reset between files. With ~2,700 tests mocking shared modules (`react`, `@chm/clickhouse-client`, `@clerk/nextjs/server`, `server-only`, …), mocks leak across files — ~78 tests passed in isolation but failed in the aggregated CI run (`React.forwardRef is not a function`, the agent-tool suites, feature-permissions, Clerk 401, …).

## Fix — native isolation, no custom runner

Use Bun's built-in **`--isolate`** (a fresh global object per test file) on the standard test scripts. No wrapper script — just a flag on `bun test`, kept in the package.json scripts that CI runs via `bun run`.

- `apps/web` `test` / `test:coverage`: add `--isolate`.
- root `test:packages` script (with `--isolate`); CI's package step calls `bun run test:packages`.
- Bump the `unit-tests` job's Bun to `1.3.13` (`--isolate` needs a recent Bun).

Also add the missing `mock.module('server-only', …)` to `dashboard-tools` and `helpers` tests — they only passed before because another file's `server-only` mock leaked in.

## Validation (local)
- agent tools dir: 38 fail (aggregated) → **0** with `--isolate`.
- full `apps/web`: 2,710 pass under `--isolate` (~4s).
- workspace `packages`: 20 fail (aggregated) → **789 pass / 0 fail**.

Pure test-infra change; no runtime code touched.

Co-Authored-By: duyetbot <bot@duyet.net>

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed context dependency tracking in table column hooks.

* **Chores**
  * Updated test infrastructure and mock patterns for improved stability.
  * Upgraded CI workflow to use newer runtime version and expanded test coverage reporting.
  * Reorganized component exports for better maintainability.
  * Enhanced environment variable handling in test suites.

[Review Change Stack](https://app.coderabbit.ai/change-stack/duyet/clickhouse-monitoring/pull/1286?utm_source=github_walkthrough&utm_medium=github&utm_campaign=change_stack)

### CODE REVIEW

**Comment by duyet** [comment]
Closing as superseded. A concurrent change already fixed the cross-file mock pollution via mock hygiene (#1283 + #1285), taking the suite 80→7. The remaining 7 failures are all genuine bugs in `browser-proxy-fetcher.test.ts` (they fail in isolation too), so the native `--isolate` approach here is both redundant with the merged hygiene fix and wouldn't resolve those genuine failures. Avoiding two competing fixes in the same files.
