### ISSUE TITLE
test: maintenance-windows.test.ts fails when health suite runs in one bun process (mock.module leak)

### ISSUE THREAD

**Issue by duyet** [duyet/clickhouse-monitoring#2672]
Found during #2656 verification (PR #2671): `apps/dashboard/src/lib/health/maintenance-windows.test.ts` fails with "createWindow is not a function" when the whole `lib/health` directory runs in a single `bun test` process, but passes in isolation. Confirmed on clean main (6 failures dir-wide). Root cause: a cross-file `mock.module` leak — another suite's module mock persists into this one.

Fix direction: scope the offending `mock.module` calls with restore in afterEach/afterAll, or switch the leaking suite to dependency injection like the newer dispatch tests. CI currently runs per-file so this only bites local full-dir runs.
